* README

Ultralisp notes is a repo for note taking related to:
https://github.com/ultralisp/ultralisp.

** Dependencies

*** Docker

**** Installation for web page
https://docs.docker.com/desktop/install/linux-install/
https://docs.docker.com/desktop/install/ubuntu/

failed

**** Installation from apt
#+begin_example
sudo apt install docker.io docker-compose
#+end_example

gives the following version
#+begin_example
docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
#+end_example

** Running it on my machine

there is an org file for that
[[file:~/Programming/Lisp/ultralisp/DEV.org::*How to start server and worker outside Docker][How to start server and worker outside Docker]]

and

https://github.com/ultralisp/ultralisp#how-to-host-ultralisp-on-my-own-server

*** after cloning the repo,
trying to run:
#+begin_example
docker-compose run --rm mito migrate
#+end_example

gives me permission errors

Why? Do I need sudo?

or
https://docs.docker.com/engine/install/linux-postinstall/

*** trying to fix permissions
#+begin_example
sudo gpasswd -a $USER docker
#+end_example

leads to another error

#+begin_example
$ docker-compose run --rm mito migrate
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

#+end_example

https://docs.docker.com/engine/install/linux-postinstall/

the fix
#+begin_example
sudo gpasswd -a $USER docker
#+end_example

#+begin_example
docker run hello-world
#+end_example

gives
#+begin_quote
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:ffb13da98453e0f04d33a6eee5bb8e46ee50d08ebe17735fc0779d0349e889e9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.
#+end_quote

it was simple cd to ultralisp diretory

#+begin_example
cd ~/Programming/Lisp/ultralisp
docker-compose run --rm mito migrate
#+end_example

gives lots of output that makes sense now
